# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a198d6c5c852993329810535c9beaa9fe583f2014fe0a2810148c23f5514794a578757718f156173491fb5d2c0ba316896e42762ebba8e26f35e3d1a146adf19

test:
  secret_key_base: d90a03b2397d050d10e93a4d89c146c5883ff81506a4502be3c2bca7e221d44b013d8bd4a8ba1391107fab80271558abfb75dc6f49354c58e0cc52bdd3aa5504

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
